# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Install Python packages
    command: |
      pyenv global 3.11
      python -m pip install -U black
  - name: Configure git
    command: curl https://gist.githubusercontent.com/donnerc/fc0312cc3431d9b3e675/raw/821a897e08e8e983a8fdf8add57e6b8cded5ed40/git-config.sh | sh
  - name: autosave
    command: source autosave.sh

image: gitpod/workspace-python-3.11

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart

vscode:
  extensions:
    - almenon.arepl
    - ms-python.python
    - littlefoxteam.vscode-python-test-adapter
    # - ms-azuretools.vscode-docker
    - laike9m.cyberbrain
